### ISSUE TITLE
[ssfic3380]CodeDeploy - deploy.sh의 Flask 앱의 로그, pid를 남기는 작업에서 권한 문제 발생

### ISSUE THREAD

**Issue by dasd412** [SWM14-Architect/moview-core-service#21]
**ssfic3380 님이 해결한 문제입니다.**

***

appspec.yml에서 유저를 ubuntu로 지정

```
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

```
