### ISSUE TITLE
[ssfic3380]EC2 내에 기존 배포 파일이 남아 있는 경우, 덮어쓰기 시 오류 발생 (기본적으로 덮어쓰기가 금지되어 있음)

### ISSUE THREAD

**Issue by dasd412** [SWM14-Architect/moview-core-service#22]
ssfic3380 님이 해결한 문제입니다.
***

### 방법 1

로그 파일이 함께 사라지는 경우가 걱정되는데,이는 /var/log에 따로 저장하거나, DB에 저장하는 것이 일반적임.그래서 app 폴더를 전체 삭제하고 배포 파일을 다시 다운로드 하는 것으로 결정

kill_flask.sh에 명령 추가

```
echo ">>> 기존에 배포된 애플리케이션 파일 제거를 시도합니다."
if [ -d "$REPOSITORY" ]; then
    echo ">>> 애플리케이션 디렉토리가 존재합니다. 삭제를 시작합니다."
    sudo rm -rf $REPOSITORY
else
    echo ">>> 애플리케이션 디렉토리가 존재하지 않습니다. 디렉토리 삭제를 스킵합니다."
fi
```

### 방법 2
appspec.yml에 overwrite: yes설정 추가

```
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes
```
→ 참고: 이 방법 되는지 안 되는지 안 해봄 ㅋㅋ
